"""Baseline schema: 15 tables, 5 enums, extensions, all required indexes.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-10

Hand-written rather than autogenerated because the partial / functional /
GIN indexes (lower(email), gin_trgm_ops, WHERE published_at IS NULL, etc.)
are invisible to Alembic autogenerate and must be emitted via raw SQL.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


# ---------------------------------------------------------------------------
# Enum types — declared with create_type=False so we control creation order.
# ---------------------------------------------------------------------------
USER_ROLE = postgresql.ENUM(
    "player", "host", "moderator", "admin", name="user_role", create_type=False
)
QUIZ_VISIBILITY = postgresql.ENUM(
    "private", "unlisted", "public", name="quiz_visibility", create_type=False
)
ROOM_STATUS = postgresql.ENUM(
    "lobby",
    "running",
    "paused",
    "completed",
    "cancelled",
    name="room_status",
    create_type=False,
)
QUESTION_TYPE = postgresql.ENUM(
    "single_choice",
    "multiple_choice",
    "true_false",
    name="question_type",
    create_type=False,
)
MODERATION_STATUS = postgresql.ENUM(
    "pending",
    "dismissed",
    "action_taken",
    name="moderation_status",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()

    # Extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gin")

    # Enum types
    USER_ROLE.create(bind, checkfirst=True)
    QUIZ_VISIBILITY.create(bind, checkfirst=True)
    ROOM_STATUS.create(bind, checkfirst=True)
    QUESTION_TYPE.create(bind, checkfirst=True)
    MODERATION_STATUS.create(bind, checkfirst=True)

    # -----------------------------------------------------------------------
    # users
    # -----------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("role", USER_ROLE, nullable=False, server_default="player"),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # -----------------------------------------------------------------------
    # quiz_tags
    # -----------------------------------------------------------------------
    op.create_table(
        "quiz_tags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_quiz_tags"),
        sa.UniqueConstraint("name", name="uq_quiz_tags_name"),
    )

    # -----------------------------------------------------------------------
    # quiz_sets
    # -----------------------------------------------------------------------
    op.create_table(
        "quiz_sets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility", QUIZ_VISIBILITY, nullable=False, server_default="private"
        ),
        sa.Column(
            "is_published", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_quiz_sets"),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name="fk_quiz_sets_owner_id_users"
        ),
    )

    # -----------------------------------------------------------------------
    # quiz_set_tags (composite PK)
    # -----------------------------------------------------------------------
    op.create_table(
        "quiz_set_tags",
        sa.Column("quiz_set_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("quiz_set_id", "tag_id", name="pk_quiz_set_tags"),
        sa.ForeignKeyConstraint(
            ["quiz_set_id"],
            ["quiz_sets.id"],
            name="fk_quiz_set_tags_quiz_set_id_quiz_sets",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["quiz_tags.id"], name="fk_quiz_set_tags_tag_id_quiz_tags"
        ),
    )

    # -----------------------------------------------------------------------
    # questions
    # -----------------------------------------------------------------------
    op.create_table(
        "questions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("quiz_set_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("type", QUESTION_TYPE, nullable=False),
        sa.Column(
            "time_limit_seconds",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("20"),
        ),
        sa.Column(
            "points", sa.Integer(), nullable=False, server_default=sa.text("1000")
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_questions"),
        sa.ForeignKeyConstraint(
            ["quiz_set_id"],
            ["quiz_sets.id"],
            name="fk_questions_quiz_set_id_quiz_sets",
        ),
        sa.UniqueConstraint(
            "quiz_set_id", "position", name="ux_questions_quiz_position"
        ),
    )

    # -----------------------------------------------------------------------
    # answer_options
    # -----------------------------------------------------------------------
    op.create_table(
        "answer_options",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "is_correct",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_answer_options"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name="fk_answer_options_question_id_questions",
        ),
        sa.UniqueConstraint(
            "question_id", "position", name="ux_answer_options_question_position"
        ),
    )

    # -----------------------------------------------------------------------
    # rooms
    # -----------------------------------------------------------------------
    op.create_table(
        "rooms",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("quiz_set_id", sa.BigInteger(), nullable=False),
        sa.Column("status", ROOM_STATUS, nullable=False, server_default="lobby"),
        sa.Column(
            "max_players", sa.Integer(), nullable=False, server_default=sa.text("50")
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_rooms"),
        sa.ForeignKeyConstraint(
            ["host_id"], ["users.id"], name="fk_rooms_host_id_users"
        ),
        sa.ForeignKeyConstraint(
            ["quiz_set_id"], ["quiz_sets.id"], name="fk_rooms_quiz_set_id_quiz_sets"
        ),
        sa.UniqueConstraint("code", name="ux_rooms_code"),
    )

    # -----------------------------------------------------------------------
    # room_participants
    # -----------------------------------------------------------------------
    op.create_table(
        "room_participants",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("nickname", sa.String(length=60), nullable=False),
        sa.Column("guest_token_hash", sa.Text(), nullable=True),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("left_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "is_kicked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_participants"),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_participants_room_id_rooms"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_room_participants_user_id_users"
        ),
    )

    # -----------------------------------------------------------------------
    # matches
    # -----------------------------------------------------------------------
    op.create_table(
        "matches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("quiz_set_version", sa.Integer(), nullable=False),
        sa.Column("status", ROOM_STATUS, nullable=False),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_matches"),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_matches_room_id_rooms"
        ),
        sa.UniqueConstraint("room_id", name="uq_matches_room_id"),
    )

    # -----------------------------------------------------------------------
    # match_questions
    # -----------------------------------------------------------------------
    op.create_table(
        "match_questions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deadline_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_match_questions"),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name="fk_match_questions_match_id_matches"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name="fk_match_questions_question_id_questions",
        ),
        sa.UniqueConstraint(
            "match_id", "position", name="ux_match_questions_match_position"
        ),
    )

    # -----------------------------------------------------------------------
    # answer_submissions
    # -----------------------------------------------------------------------
    op.create_table(
        "answer_submissions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("match_question_id", sa.BigInteger(), nullable=False),
        sa.Column("participant_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "selected_option_ids",
            postgresql.ARRAY(sa.BigInteger()),
            nullable=False,
        ),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("score_awarded", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_answer_submissions"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name="fk_answer_submissions_match_id_matches",
        ),
        sa.ForeignKeyConstraint(
            ["match_question_id"],
            ["match_questions.id"],
            name="fk_answer_submissions_match_question_id_match_questions",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["room_participants.id"],
            name="fk_answer_submissions_participant_id_room_participants",
        ),
        sa.UniqueConstraint(
            "match_question_id", "participant_id", name="ux_submission_once"
        ),
        sa.UniqueConstraint("request_id", name="ux_submission_request"),
    )

    # -----------------------------------------------------------------------
    # final_scores (composite PK)
    # -----------------------------------------------------------------------
    op.create_table(
        "final_scores",
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("participant_id", sa.BigInteger(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("average_response_ms", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("match_id", "participant_id", name="pk_final_scores"),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name="fk_final_scores_match_id_matches"
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["room_participants.id"],
            name="fk_final_scores_participant_id_room_participants",
        ),
    )

    # -----------------------------------------------------------------------
    # moderation_reports
    # -----------------------------------------------------------------------
    op.create_table(
        "moderation_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("reporter_user_id", sa.BigInteger(), nullable=True),
        sa.Column("room_id", sa.BigInteger(), nullable=True),
        sa.Column("target_user_id", sa.BigInteger(), nullable=True),
        sa.Column("target_quiz_set_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "status", MODERATION_STATUS, nullable=False, server_default="pending"
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_moderation_reports"),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name="fk_moderation_reports_reporter_user_id_users",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_moderation_reports_room_id_rooms"
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name="fk_moderation_reports_target_user_id_users",
        ),
        sa.ForeignKeyConstraint(
            ["target_quiz_set_id"],
            ["quiz_sets.id"],
            name="fk_moderation_reports_target_quiz_set_id_quiz_sets",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name="fk_moderation_reports_reviewed_by_users",
        ),
    )

    # -----------------------------------------------------------------------
    # audit_logs
    # -----------------------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_audit_logs"),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name="fk_audit_logs_actor_user_id_users",
        ),
    )

    # -----------------------------------------------------------------------
    # outbox_events
    # -----------------------------------------------------------------------
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "publish_attempts",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_outbox_events"),
    )

    # -----------------------------------------------------------------------
    # Standard indexes (per docs/05 §"Required indexes")
    # -----------------------------------------------------------------------
    op.create_index(
        "ix_quiz_sets_owner_created",
        "quiz_sets",
        ["owner_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_rooms_host_created",
        "rooms",
        ["host_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_room_participants_room_user",
        "room_participants",
        ["room_id", "user_id"],
    )
    op.create_index(
        "ix_submissions_match_participant",
        "answer_submissions",
        ["match_id", "participant_id"],
    )
    op.create_index(
        "ix_final_scores_rank", "final_scores", ["match_id", "rank"]
    )
    op.create_index(
        "ix_outbox_published_occurred",
        "outbox_events",
        ["published_at", "occurred_at"],
    )
    op.create_index(
        "ix_outbox_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id"],
    )

    # -----------------------------------------------------------------------
    # Functional / partial / GIN indexes (raw SQL — autogenerate cannot describe)
    # -----------------------------------------------------------------------
    op.execute(
        "CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email))"
    )
    op.execute(
        "CREATE INDEX ix_quiz_sets_public_published ON quiz_sets (created_at DESC) "
        "WHERE visibility = 'public' AND is_published = true"
    )
    op.execute(
        "CREATE INDEX ix_quiz_sets_title_trgm ON quiz_sets "
        "USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_room_participant_nickname "
        "ON room_participants (room_id, lower(nickname))"
    )
    op.execute(
        "CREATE INDEX ix_outbox_unpublished ON outbox_events (occurred_at) "
        "WHERE published_at IS NULL"
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Drop functional / partial / GIN indexes (must precede table drops in
    # case the planner needs them, and they cannot be dropped via op.drop_index
    # without the original ddl signature in some Alembic versions).
    op.execute("DROP INDEX IF EXISTS ix_outbox_unpublished")
    op.execute("DROP INDEX IF EXISTS ux_room_participant_nickname")
    op.execute("DROP INDEX IF EXISTS ix_quiz_sets_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_quiz_sets_public_published")
    op.execute("DROP INDEX IF EXISTS ux_users_email_lower")

    # Standard indexes (only those not auto-dropped with their tables — most
    # are, but we drop named ones explicitly to keep downgrade idempotent).
    for ix in (
        "ix_outbox_aggregate",
        "ix_outbox_published_occurred",
        "ix_final_scores_rank",
        "ix_submissions_match_participant",
        "ix_room_participants_room_user",
        "ix_rooms_host_created",
        "ix_quiz_sets_owner_created",
    ):
        op.execute(f"DROP INDEX IF EXISTS {ix}")

    # Tables in reverse FK order
    for table in (
        "outbox_events",
        "audit_logs",
        "moderation_reports",
        "final_scores",
        "answer_submissions",
        "match_questions",
        "matches",
        "room_participants",
        "rooms",
        "answer_options",
        "questions",
        "quiz_set_tags",
        "quiz_sets",
        "quiz_tags",
        "users",
    ):
        op.drop_table(table)

    # Enums
    MODERATION_STATUS.drop(bind, checkfirst=True)
    QUESTION_TYPE.drop(bind, checkfirst=True)
    ROOM_STATUS.drop(bind, checkfirst=True)
    QUIZ_VISIBILITY.drop(bind, checkfirst=True)
    USER_ROLE.drop(bind, checkfirst=True)

    # Extensions intentionally left in place — they may be shared with other
    # databases on the same cluster, and dropping would cascade.
